### ISSUE TITLE
Add a command like /nwl add offline

### ISSUE THREAD

**Issue by IasonKalaitzakis** [NobelD/NobleWhitelist#6]
I am transitioning from the vanilla whitelist to this plugin, and I would love a command that adds every person that has ever joined to the whitelist. Thanks :)

**Comment by NobelD** [comment]
hi, this function will be tracked in #10
there you can find a light plugin in case you want to use the function earlier
it is an add-on so it is necessary to have the base plugin
this function will be later added to the base plugin

thanks!
