### ISSUE TITLE
Unclear meaning of the parameter 'checking', inconsistent behaviour

### ISSUE THREAD

**Issue by Vagor96** [NobelD/NobleWhitelist#8]
### Version
Plugin version: 1.2.4
Paper version: 1.21.1-39

### Description
The "checking" setting seems to do something different than you would expect. What does *OPTIONAL* mean and what does *REQUIRED* mean? From my point of view is the setting *checking* a boolean variable and should therefore only accept the values *true* and *false*. For example the uuid can either be checked or not. But if it is checked "optionally", then that is the same as not being checked.

I certainly misunderunderstood something about the naming of this setting, but regardless of the naming does the plugin not seem to behave consistently.

Here are some concrete test scenarios to make it clear what I mean. I used a MySQL database as data store.

**1. name: DISABLED, uuid: DISABLED, perm: DISABLED**
Expected: Joining always possible (The comments in the configuration file say "if all disabled, then the whitelist will not block players even if its enabled".)
Actually:
- Player not in database: *Joining not possible* :x:
- nwl add name: *Joining not possible* :x:
- nwl add uuid: *Joining is possible* :white_check_mark:

**2. name: DISABLED, uuid: REQUIRED, perm: DISABLED**
Expected: Joining only possible if uuid in whitelist
Actually:
- Player not in database: *Joining not possible* :white_check_mark:
- nwl add name: *Joining not possible* :white_check_mark:
- nwl add uuid: *Joining **exactly once** possible*. As long as the name is NULL in the database, you can join. If NULL has been replaced by the real name after the first join, you can no longer join. :x:

**3. name: OPTIONAL, uuid: REQUIRED, perm: DISABLED**
see 2) :x:

**4. name: DISABLED, uuid: OPTIONAL, perm: DISABLED**
Expected: Joining always possible, since the UUID only has to match optionally?
In fact:
- Player not in database: *Joining not possible* :grey_question: (:white_check_mark: if value had been named 'true')
- nwl add name: *Joining not possible* :grey_question: (:white_check_mark: if value had been named 'true')
- nwl add uuid: *Joining possible* :grey_question: (:white_check_mark: if value had been named 'true')

**5. name: OPTIONAL, uuid: OPTIONAL, perm: DISABLED**
Expected: Joining always possible, since name and UUID only have to match optionally?
In fact:
- Player not in database: *Joining not possible* :grey_question: (:white_check_mark: if value had been named 'true')
- nwl add name: *Joining possible* :grey_question: (:white_check_mark: if value had been named 'true')
- nwl add uuid: *Joining possible* :grey_question: (:white_check_mark: if value had been named 'true')

In my opinion, this seems - at least partially - to be a bug. Case 1 behaves contrary to the documentation. The cases 2 and 3 do not seem to work at all. Cases 4 and 5 are what you would expect if the keyword optional was not called "optional" but rather true (the name/uuid/permission can be used to login) and false (it can not be used to login).

Nevertheless, thank you very much for the plugin! If I misunderstood the setting, I would be happy if you could explain it to me and perhaps adjust the documentation to prevent further missunderstandings.

**Comment by NobelD** [comment]
Hi, the documentation seems to be getting a bit confusing and I've already heard that from a few people.
I'm currently working on expanding it with its own page, to one external to github wiki where I'll be able to detail it more!!

about disabled and optional they have a little difference, while disabled simply ignores the result, optional makes sure at least one passes.

Example 1: (name = Optional, uuid = Optional)
yes name - no uuid -> allows
no name - no uuid -> block
no name - yes uuid -> allows
yes name - yea uuid -> allows

Example 2: (name = Disabled, uuid = Disabled)
yes name - no uuid -> allows
no name - no uuid -> allows
no name - yes uuid -> allows
yes name - yes uuid -> allows

And well, required must always comply with that one to allow.

After looking over the code I realized that in certain cases it simply skips some options when there are multiple combinations (just what you say), so I will have to redo that part to make it fit the above examples and stay consistent in different cases.

I will look into expanding the documentation of those options within the plugin as well.
As well as adding examples to understand how it works

An apology for the bug and thanks for reporting it, some details escape being somewhat specific scenarios, every comment helps to improve the plugin, thx again! :D
