### ISSUE TITLE
Vanilla Whitelist Import?

### ISSUE THREAD

**Issue by LadyHaley** [NobelD/NobleWhitelist#9]
I cant see any information about it, how do I import a vanilla whitelist file to the plugin data storage? I have a whitelist file that is hundreds of players large and cant be expected to manually import almost 1500 users over to a new plugin manually

**Comment by NobelD** [comment]
hi, this function will be tracked in #10
there you can find a light plugin in case you want to use the function earlier
it is an add-on so it is necessary to have the base plugin
this function will be later added to the base plugin

thanks!

**Comment by LadyHaley** [comment]
Thank you!! Would you also consider adding an option to have the plugin also use the vanilla whitelist file along side the plugins current data storage when adding and removing users from the whitelist. This would help to have a fallback for if theres some sort of plugin issue, or data loss from a sql database or any other worst case scenario. It would also help to ensure compatibility with any plugin that might read data from the default whitelist file, like DiscordSRV for example with its account linking system, which requires accounts to be linked through their bot, but has an option to not require that for whitelisted users. I personally use the DiscordSRV bot to sync my support roles to the mc server

**Comment by NobelD** [comment]
hii, yes I could add it, although I will look for a correct way to implement it
the vanilla whitelist is stored in an array, so a lot of continuous changes and specially when there are a lot of entries maybe can impact on performance
in any case I would end up adding it experimentally, only for those who know how to use it ^^

and thanks for mentioning DiscordSRV, I was modifying the discord plugin to integrate with other plugins that connect to discord
so it can reduce resource usage, and they can manage all that part from another known plugin
I'll keep an eye on that, thx!
